[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: ~/printer_data/comms/klippy.sock

[authorization]
cors_domains:
  http://jerkmaster.local:8080
  http://jerkmaster.home:8080
  http://*.local
  http://*.local:8080
  http://*.home
  http://*.home:8080
trusted_clients:
  127.0.0.0/8
  192.168.0.0/16
  10.0.0.0/8

[octoprint_compat]

[history]

[announcements]
subscriptions:
  moonraker

[file_manager]
enable_object_processing: False

[update_manager]
refresh_interval: 168
